### ISSUE TITLE
Amazon CloudFront?

### ISSUE THREAD

**Issue by davidray** [nazar/jw-playr-hlpr#1]
Any thoughts on making this work with cloudfront?

**Comment by nazar** [comment]
There appears to be some discussion on this [here](http://www.longtailvideo.com/support/forums/jw-player/setup-issues-and-embedding/9426/cloudfront-rtmp-streaming).

I personally have no plans on adding this feature jw-playr-hlpr as it is currently in production on a few of my sites. You are, however, more than welcome to fork either my or any of the more recent forks and add this feature.

All the best.

**Comment by davidray** [comment]
Cool, thanks. I got it working on the v5 player without your helper... maybe I'll re-factor it as a helper later though.
